# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RentaTeamTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RentaTeamTest

 pod 'Alamofire', '~> 5.2'
 pod 'SwiftyJSON', '~> 4.0'

end
